"""Remediation and installation guidance services."""
from __future__ import annotations

import platform
from typing import Dict, Optional

from .environment import EnvironmentService


class FixService:
    """Provide safe remediation guidance (no privileged execution)."""

    def __init__(self, environment_service: EnvironmentService) -> None:
        self._environment = environment_service

    def docker_install_script(self) -> Optional[str]:
        os_type = platform.system()
        if os_type != "Linux":
            return None

        distro = self._detect_linux_distro()
        if distro in {"ubuntu", "debian"}:
            return _UBUNTU_SCRIPT
        if distro in {"fedora", "centos", "rhel"}:
            return _FEDORA_SCRIPT
        return None

    def docker_instructions(self) -> Dict[str, object]:
        os_type = platform.system()
        if os_type == "Darwin":
            return _MAC_INSTRUCTIONS
        if os_type == "Windows":
            return _WINDOWS_INSTRUCTIONS

        distro = self._detect_linux_distro()
        if distro == "unknown":
            return _LINUX_GENERIC_INSTRUCTIONS

        return {
            "platform": f"Linux ({distro.title()})",
            "method": "script",
            "download_url": "/api/fix/docker/install-script",
            "instructions": [
                "📥 Download and run the installation script:",
                "  curl -fsSL http://localhost:5001/api/fix/docker/install-script > install-docker.sh",
                "  chmod +x install-docker.sh",
                "  ./install-docker.sh",
                "",
                "⚠️  You will need sudo privileges",
            ],
        }

    def check_docker(self) -> Dict[str, object]:
        return self._environment.check_docker()

    @staticmethod
    def _detect_linux_distro() -> str:
        try:
            with open("/etc/os-release", "r", encoding="utf-8") as handle:
                content = handle.read().lower()
            if "ubuntu" in content:
                return "ubuntu"
            if "debian" in content:
                return "debian"
            if "fedora" in content:
                return "fedora"
            if "centos" in content:
                return "centos"
            if "red hat" in content or "rhel" in content:
                return "rhel"
        except FileNotFoundError:
            pass
        return "unknown"


_UBUNTU_SCRIPT = """#!/bin/bash
# Docker installation script for Ubuntu/Debian
# Generated by Staker Agent

set -e

echo "Installing Docker..."
sudo apt-get update -qq
sudo apt-get install -y docker.io docker-compose-v2
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER

echo ""
echo "✅ Docker installed successfully!"
echo "⚠️  Please log out and log back in, or run: newgrp docker"
"""


_FEDORA_SCRIPT = """#!/bin/bash
# Docker installation script for Fedora/RHEL/CentOS
# Generated by Staker Agent

set -e

echo "Installing Docker..."
sudo dnf install -y docker docker-compose
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER

echo ""
echo "✅ Docker installed successfully!"
echo "⚠️  Please log out and log back in"
"""


_MAC_INSTRUCTIONS = {
    "platform": "macOS",
    "method": "manual",
    "instructions": [
        "🍺 Option 1: Homebrew (Recommended)",
        "  brew install --cask docker",
        "",
        "🌐 Option 2: Official Website",
        "  1. Visit https://www.docker.com/products/docker-desktop",
        "  2. Download Docker Desktop for Mac",
        "  3. Install and launch Docker Desktop",
        "  4. Wait for Docker engine to start",
        "",
        "✅ Verify installation:",
        "  docker --version",
    ],
}


_WINDOWS_INSTRUCTIONS = {
    "platform": "Windows",
    "method": "manual",
    "instructions": [
        "🌐 Docker Desktop Installation",
        "  1. Visit https://www.docker.com/products/docker-desktop",
        "  2. Download Docker Desktop for Windows",
        "  3. Run the installer",
        "  4. Enable WSL 2 if prompted",
        "  5. Restart your computer",
        "  6. Launch Docker Desktop",
        "",
        "✅ Verify installation:",
        "  docker --version",
    ],
}


_LINUX_GENERIC_INSTRUCTIONS = {
    "platform": "Linux (Unknown Distribution)",
    "method": "manual",
    "instructions": [
        "📋 Use the official Docker installation script:",
        "  curl -fsSL https://get.docker.com -o get-docker.sh",
        "  sudo sh get-docker.sh",
        "",
        "Or visit: https://docs.docker.com/engine/install/",
    ],
}
