"""
Configuration generator for eth-docker
"""
import os
import yaml
from pathlib import Path
from rich.console import Console

from core.validation import validate_evm_address

console = Console()

class ConfigGenerator:
    def __init__(self, eth_docker_path: str):
        self.eth_docker_path = eth_docker_path
        self.config_path = Path(__file__).parent.parent.parent / 'config' / 'networks.yaml'

        with open(self.config_path, 'r') as f:
            self.config = yaml.safe_load(f)

    def generate_env(self, network='holesky', client='lighthouse', fee_recipient=None, withdrawal_address=None):
        """Generate .env file for eth-docker"""
        if fee_recipient:
            validate_evm_address(fee_recipient, "fee_recipient")
        if withdrawal_address:
            validate_evm_address(withdrawal_address, "withdrawal_address")

        network_config = self.config['networks'].get(network)
        if not network_config:
            console.print(f"[red]❌ Unknown network: {network}[/red]")
            return False

        client_config = self.config['clients'].get(client)
        if not client_config:
            console.print(f"[red]❌ Unknown client: {client}[/red]")
            return False

        # Map network names to eth-docker format
        network_map = {
            'mainnet': 'mainnet',
            'hoodi': 'hoodi',
            'holesky': 'holesky',
            'sepolia': 'sepolia'
        }

        # Map client names to eth-docker compose file format
        # eth-docker uses : to separate multiple yml files
        compose_map = {
            'lighthouse': 'lighthouse.yml:geth.yml:deposit-cli.yml',
            'prysm': 'prysm.yml:geth.yml:deposit-cli.yml',
            'teku': 'teku.yml:geth.yml:deposit-cli.yml',
            'nimbus': 'nimbus.yml:geth.yml:deposit-cli.yml'
        }

        env_content = f"""# Generated by Staker Agent
# Network: {network}
# Client: {client}

# Compose file selection
# eth-docker uses : to separate multiple service files
COMPOSE_FILE={compose_map[client]}

# Network selection
NETWORK={network_map[network]}

# Graffiti for consensus client
GRAFFITI=Staker-Agent

# JWT secret for EL-CL communication (auto-generated)
JWT_SECRET=

# Execution Layer settings
EL_NODE=http://execution:8551
GETH_DOCKERFILE=Dockerfile.binary
EL_P2P_PORT=30303

# Consensus Layer settings
CL_NODE=http://consensus:5052
"""

        # Add client-specific configuration
        if client == 'lighthouse':
            env_content += """LH_DOCKERFILE=Dockerfile.binary
"""
        elif client == 'prysm':
            env_content += """PRYSM_DOCKERFILE=Dockerfile.binary
PRYSM_HOST=prysm
PRYSM_PORT=9000
PRYSM_UDP_PORT=9000
CL_QUIC_PORT=9001
PRYSM_DOCKER_TAG=stable
PRYSM_DOCKER_VC_TAG=stable
PRYSM_DOCKER_CTL_TAG=stable
PRYSM_DOCKER_REPO=gcr.io/prysmaticlabs/prysm/beacon-chain
PRYSM_DOCKER_VC_REPO=gcr.io/prysmaticlabs/prysm/validator
PRYSM_DOCKER_CTL_REPO=gcr.io/prysmaticlabs/prysm/cmd/prysmctl
"""
        elif client == 'teku':
            env_content += """TEKU_DOCKERFILE=Dockerfile.binary
TEKU_DOCKER_TAG=latest
"""
        elif client == 'nimbus':
            env_content += """NIMBUS_DOCKERFILE=Dockerfile.binary
NIMBUS_DOCKER_TAG=multiarch-latest
"""

        env_content += """CL_P2P_PORT=9000
LOG_LEVEL=info

# Validator settings
DOPPELGANGER=true

# Deposit CLI settings
DEPCLI_DOCKERFILE=Dockerfile.binary

# Metrics and monitoring
METRICS=true
PROM_PORT=9090
GRAFANA_PORT=3000

# Beacon stats (optional)
BEACON_STATS_API=
BEACON_STATS_MACHINE=

# MEV-Boost (disabled by default)
MEV_BOOST=
MEV_NODE=

# Web3Signer (disabled by default)
W3S_NODE=

# Domain for SSL (optional)
DOMAIN=

"""

        # Add fee recipient if provided
        if fee_recipient:
            env_content += f"# Fee recipient address\nFEE_RECIPIENT={fee_recipient}\n\n"
        elif network == 'mainnet':
            # Mainnet requires a fee recipient
            env_content += "# Fee recipient address (REQUIRED for mainnet)\n# Set this to your Ethereum address to receive transaction fees\n# FEE_RECIPIENT=0x...\n\n"
        else:
            # Testnets: use a default burn address
            env_content += "# Fee recipient address (optional for testnet)\nFEE_RECIPIENT=0x0000000000000000000000000000000000000000\n\n"

        # Add withdrawal address if provided (for Lido CSM)
        if withdrawal_address:
            env_content += f"# Withdrawal address\nWITHDRAWAL_ADDRESS={withdrawal_address}\n\n"

        # Add checkpoint sync URLs per network
        checkpoint_urls = {
            'mainnet': 'https://beaconstate.ethstaker.cc',
            'hoodi': 'https://checkpoint-sync.hoodi.ethpandaops.io',
            'holesky': 'https://checkpoint-sync.holesky.ethpandaops.io',
            'sepolia': 'https://checkpoint-sync.sepolia.ethpandaops.io'
        }

        env_content += f"""# Enable checkpoint sync for faster initial sync
CHECKPOINT_SYNC=true
CHECKPOINT_SYNC_URL={checkpoint_urls.get(network, '')}

"""

        # Add resource limits
        requirements = self.config['requirements'].get(network, {})
        env_content += f"""# Resource requirements for {network}
# Storage: {requirements.get('storage_gb', 100)}GB+
# RAM: {requirements.get('ram_gb', 8)}GB+
# CPU: {requirements.get('cpu_cores', 2)}+ cores

# Docker resource limits (optional)
# Uncomment and adjust as needed
# EL_MEMORY_LIMIT=8g
# CL_MEMORY_LIMIT=4g
"""

        # Write .env file
        env_path = os.path.join(self.eth_docker_path, '.env')
        try:
            with open(env_path, 'w') as f:
                f.write(env_content)
            console.print(f"[green]✅ Configuration written to {env_path}[/green]")
            return True
        except Exception as e:
            console.print(f"[red]❌ Failed to write configuration: {str(e)}[/red]")
            return False

    def show_config(self):
        """Display current configuration"""
        env_path = os.path.join(self.eth_docker_path, '.env')
        if os.path.exists(env_path):
            with open(env_path, 'r') as f:
                console.print("[cyan]Current configuration:[/cyan]\n")
                console.print(f.read())
            return True
        else:
            console.print("[yellow]⚠️  No configuration found. Run 'configure' first.[/yellow]")
            return False

    def validate_config(self):
        """Validate the configuration"""
        env_path = os.path.join(self.eth_docker_path, '.env')
        if not os.path.exists(env_path):
            console.print("[red]❌ No .env file found[/red]")
            return False

        # Check required files exist
        required_files = ['docker-compose.yml']
        for file in required_files:
            file_path = os.path.join(self.eth_docker_path, file)
            if not os.path.exists(file_path):
                console.print(f"[red]❌ Missing required file: {file}[/red]")
                return False

        console.print("[green]✅ Configuration is valid[/green]")
        return True
