"""
Fix API - Safe installation guidance (NOT automatic execution)

NEVER execute shell=True + sudo in a web API!
We return scripts for users to execute manually.
"""
from flask import Blueprint, jsonify, Response
import platform

fix_bp = Blueprint('fix', __name__)


@fix_bp.route('/docker/install-script', methods=['GET'])
def get_docker_install_script():
    """
    Return installation script as plain text.
    User downloads and executes it themselves.
    This is safe. Automatic sudo execution is NOT.
    """
    os_type = platform.system()

    if os_type == 'Linux':
        # Detect distro from /etc/os-release
        distro = _detect_linux_distro()

        if distro in ['ubuntu', 'debian']:
            script = """#!/bin/bash
# Docker installation script for Ubuntu/Debian
# Generated by Staker Agent

set -e

echo "Installing Docker..."
sudo apt-get update -qq
sudo apt-get install -y docker.io docker-compose-v2
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER

echo ""
echo "✅ Docker installed successfully!"
echo "⚠️  Please log out and log back in, or run: newgrp docker"
"""
            return Response(script, mimetype='text/x-shellscript')

        elif distro in ['fedora', 'centos', 'rhel']:
            script = """#!/bin/bash
# Docker installation script for Fedora/RHEL/CentOS
# Generated by Staker Agent

set -e

echo "Installing Docker..."
sudo dnf install -y docker docker-compose
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker $USER

echo ""
echo "✅ Docker installed successfully!"
echo "⚠️  Please log out and log back in"
"""
            return Response(script, mimetype='text/x-shellscript')

    # For macOS/Windows or unsupported distros, return JSON instructions
    return jsonify(_get_manual_instructions(os_type))


@fix_bp.route('/docker/instructions', methods=['GET'])
def get_docker_instructions():
    """Get installation instructions in JSON format"""
    os_type = platform.system()
    return jsonify(_get_manual_instructions(os_type))


@fix_bp.route('/docker/check', methods=['GET'])
def check_docker_status():
    """
    Check Docker status without executing anything.
    Safe for web API.
    """
    from core.system_checker import SystemChecker

    result = SystemChecker.check_docker()

    return jsonify({
        'success': True,
        'installed': result.passed,
        'version': result.value,
        'error': result.error
    })


def _detect_linux_distro() -> str:
    """Detect Linux distribution"""
    try:
        with open('/etc/os-release', 'r') as f:
            content = f.read().lower()

        if 'ubuntu' in content:
            return 'ubuntu'
        elif 'debian' in content:
            return 'debian'
        elif 'fedora' in content:
            return 'fedora'
        elif 'centos' in content:
            return 'centos'
        elif 'red hat' in content or 'rhel' in content:
            return 'rhel'
    except Exception:
        pass

    return 'unknown'


def _get_manual_instructions(os_type: str) -> dict:
    """Get manual installation instructions"""

    if os_type == 'Darwin':  # macOS
        return {
            'platform': 'macOS',
            'method': 'manual',
            'instructions': [
                '🍺 Option 1: Homebrew (Recommended)',
                '  brew install --cask docker',
                '',
                '🌐 Option 2: Official Website',
                '  1. Visit https://www.docker.com/products/docker-desktop',
                '  2. Download Docker Desktop for Mac',
                '  3. Install and launch Docker Desktop',
                '  4. Wait for Docker engine to start',
                '',
                '✅ Verify installation:',
                '  docker --version'
            ]
        }

    elif os_type == 'Windows':
        return {
            'platform': 'Windows',
            'method': 'manual',
            'instructions': [
                '🌐 Docker Desktop Installation',
                '  1. Visit https://www.docker.com/products/docker-desktop',
                '  2. Download Docker Desktop for Windows',
                '  3. Run the installer',
                '  4. Enable WSL 2 if prompted',
                '  5. Restart your computer',
                '  6. Launch Docker Desktop',
                '',
                '✅ Verify installation:',
                '  docker --version'
            ]
        }

    else:  # Linux or unknown
        distro = _detect_linux_distro()

        if distro == 'unknown':
            return {
                'platform': 'Linux (Unknown Distribution)',
                'method': 'manual',
                'instructions': [
                    '📋 Use the official Docker installation script:',
                    '  curl -fsSL https://get.docker.com -o get-docker.sh',
                    '  sudo sh get-docker.sh',
                    '',
                    'Or visit: https://docs.docker.com/engine/install/'
                ]
            }

        return {
            'platform': f'Linux ({distro.title()})',
            'method': 'script',
            'download_url': '/api/fix/docker/install-script',
            'instructions': [
                f'📥 Download and run the installation script:',
                f'  curl -fsSL http://localhost:5001/api/fix/docker/install-script > install-docker.sh',
                f'  chmod +x install-docker.sh',
                f'  ./install-docker.sh',
                '',
                '⚠️  You will need sudo privileges'
            ]
        }
