"""
Configuration generator for eth-docker
"""
import os
import yaml
from pathlib import Path
from rich.console import Console

console = Console()

class ConfigGenerator:
    def __init__(self, eth_docker_path=None):
        self.eth_docker_path = eth_docker_path or os.path.expanduser('~/eth-docker')
        self.config_path = Path(__file__).parent.parent / 'config' / 'networks.yaml'

        with open(self.config_path, 'r') as f:
            self.config = yaml.safe_load(f)

    def generate_env(self, network='holesky', client='lighthouse', fee_recipient=None, withdrawal_address=None):
        """Generate .env file for eth-docker"""

        network_config = self.config['networks'].get(network)
        if not network_config:
            console.print(f"[red]❌ Unknown network: {network}[/red]")
            return False

        client_config = self.config['clients'].get(client)
        if not client_config:
            console.print(f"[red]❌ Unknown client: {client}[/red]")
            return False

        # Map network names to eth-docker format
        network_map = {
            'mainnet': 'mainnet',
            'holesky': 'holesky',
            'hoodi': 'hoodi',
            'sepolia': 'sepolia'
        }

        # Map client names to eth-docker compose file format
        # eth-docker uses : to separate multiple yml files
        compose_map = {
            'lighthouse': 'lighthouse.yml:geth.yml:deposit-cli.yml',
            'prysm': 'prysm.yml:geth.yml:deposit-cli.yml',
            'teku': 'teku.yml:geth.yml:deposit-cli.yml',
            'nimbus': 'nimbus.yml:geth.yml:deposit-cli.yml'
        }

        env_content = f"""# Generated by Staker Agent
# Network: {network}
# Client: {client}

# Compose file selection
# eth-docker uses : to separate multiple service files
COMPOSE_FILE={compose_map[client]}

# Network selection
NETWORK={network_map[network]}

# Graffiti for consensus client
GRAFFITI=Staker-Agent

"""

        # Add fee recipient if provided
        if fee_recipient:
            env_content += f"# Fee recipient address\nFEE_RECIPIENT={fee_recipient}\n\n"

        # Add withdrawal address if provided (for Lido CSM)
        if withdrawal_address:
            env_content += f"# Withdrawal address\nWITHDRAWAL_ADDRESS={withdrawal_address}\n\n"

        # Add Lido CSM specific config for hoodi
        if network == 'hoodi':
            env_content += """# Lido CSM Configuration
# Set the fee recipient to Lido's execution layer rewards vault
FEE_RECIPIENT=0xE73a3602b99f1f913e72F8bdcBC235e206794Ac8

# MEV-Boost configuration
# Uncomment to use MEV-Boost with Lido
# MEV_BOOST=true
# MEV_RELAYS=https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net

"""

        env_content += """# Port configuration
# Execution layer P2P port
EL_P2P_PORT=30303

# Consensus layer P2P port
CL_P2P_PORT=9000

# Enable metrics
METRICS=true

# Prometheus port
PROM_PORT=9090

# Grafana port
GRAFANA_PORT=3000

# Enable checkpoint sync for faster initial sync
CHECKPOINT_SYNC=true

# Checkpoint sync URL
"""

        # Add checkpoint sync URLs per network
        checkpoint_urls = {
            'mainnet': 'https://beaconstate.ethstaker.cc',
            'holesky': 'https://checkpoint-sync.holesky.ethpandaops.io',
            'hoodi': 'https://checkpoint-sync.hoodi.lido.fi',
            'sepolia': 'https://checkpoint-sync.sepolia.ethpandaops.io'
        }

        env_content += f"CHECKPOINT_SYNC_URL={checkpoint_urls.get(network, '')}\n\n"

        # Add resource limits
        requirements = self.config['requirements'].get(network, {})
        env_content += f"""# Resource requirements for {network}
# Storage: {requirements.get('storage_gb', 100)}GB+
# RAM: {requirements.get('ram_gb', 8)}GB+
# CPU: {requirements.get('cpu_cores', 2)}+ cores

# Docker resource limits (optional)
# Uncomment and adjust as needed
# EL_MEMORY_LIMIT=8g
# CL_MEMORY_LIMIT=4g
"""

        # Write .env file
        env_path = os.path.join(self.eth_docker_path, '.env')
        try:
            with open(env_path, 'w') as f:
                f.write(env_content)
            console.print(f"[green]✅ Configuration written to {env_path}[/green]")
            return True
        except Exception as e:
            console.print(f"[red]❌ Failed to write configuration: {str(e)}[/red]")
            return False

    def show_config(self):
        """Display current configuration"""
        env_path = os.path.join(self.eth_docker_path, '.env')
        if os.path.exists(env_path):
            with open(env_path, 'r') as f:
                console.print("[cyan]Current configuration:[/cyan]\n")
                console.print(f.read())
            return True
        else:
            console.print("[yellow]⚠️  No configuration found. Run 'configure' first.[/yellow]")
            return False

    def validate_config(self):
        """Validate the configuration"""
        env_path = os.path.join(self.eth_docker_path, '.env')
        if not os.path.exists(env_path):
            console.print("[red]❌ No .env file found[/red]")
            return False

        # Check required files exist
        required_files = ['docker-compose.yml']
        for file in required_files:
            file_path = os.path.join(self.eth_docker_path, file)
            if not os.path.exists(file_path):
                console.print(f"[red]❌ Missing required file: {file}[/red]")
                return False

        console.print("[green]✅ Configuration is valid[/green]")
        return True
